"""add_role_requests_table

Revision ID: 0a11914944b8
Revises: 
Create Date: 2026-04-25 16:39:14.760636

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '0a11914944b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'razorpay_order_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('orders_org_id_idx', table_name='orders')
    op.create_index(op.f('ix_orders_org_id'), 'orders', ['org_id'], unique=False)
    op.alter_column('orgs', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('orgs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('orgs', 'razorpay_sub_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('orgs_slug_idx', table_name='orgs')
    op.drop_constraint('orgs_slug_key', 'orgs', type_='unique')
    op.create_index(op.f('ix_orgs_slug'), 'orgs', ['slug'], unique=True)
    op.alter_column('products', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('products_org_id_idx', table_name='products')
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index('users_firebase_uid_idx', table_name='users')
    op.drop_constraint('users_firebase_uid_key', 'users', type_='unique')
    op.drop_index('users_org_id_idx', table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index('users_org_id_idx', 'users', ['org_id'], unique=False)
    op.create_unique_constraint('users_firebase_uid_key', 'users', ['firebase_uid'])
    op.create_index('users_firebase_uid_idx', 'users', ['firebase_uid'], unique=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.create_index('products_org_id_idx', 'products', ['org_id'], unique=False)
    op.alter_column('products', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_orgs_slug'), table_name='orgs')
    op.create_unique_constraint('orgs_slug_key', 'orgs', ['slug'])
    op.create_index('orgs_slug_idx', 'orgs', ['slug'], unique=False)
    op.alter_column('orgs', 'razorpay_sub_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('orgs', 'name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orgs', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_org_id'), table_name='orders')
    op.create_index('orders_org_id_idx', 'orders', ['org_id'], unique=False)
    op.alter_column('orders', 'razorpay_order_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
